In [1]:
# import necessary libraries

import pandas as pd
import numpy as np
import matplotlib as plt

In [2]:
# show all numeric columns as float
pd.options.display.float_format = '{:.2f}'.format

In [3]:
#import data

employees = pd.read_csv('employees.csv')

In [4]:
# preview the data

employees.shape

(105, 5)

In [5]:
employees.dtypes

User_ID       float64
Name           object
Join_Date      object
Salary        float64
Department     object
dtype: object

In [6]:
employees.columns

Index(['User_ID', 'Name', 'Join_Date', 'Salary', 'Department'], dtype='object')

In [7]:
employees.head()

   User_ID     Name   Join_Date     Salary Department
0   101.00    Alice  2023-01-01   75000.00         IT
1   102.00      Bob  01-05-2023   82000.00      Sales
2   103.00  Charlie  2023-03-15        NaN  Marketing
3   101.00    Alice  2023-01-01   75000.00         IT
4   104.00    David  2023-04-20 9999999.00         HR

In [8]:
# Experiment to change column names
employees = employees.rename(columns={'UserID': 'EmployeeID', 'First Name': 'FirstName', 'Join_Date': 'HireDate', 'Salary': 'Compensation', 'Department': 'Dept'})
employees.columns

Index(['User_ID', 'Name', 'HireDate', 'Compensation', 'Dept'], dtype='object')

In [9]:
# preview the data again to see the changes

employees.head()

   User_ID     Name    HireDate  Compensation       Dept
0   101.00    Alice  2023-01-01      75000.00         IT
1   102.00      Bob  01-05-2023      82000.00      Sales
2   103.00  Charlie  2023-03-15           NaN  Marketing
3   101.00    Alice  2023-01-01      75000.00         IT
4   104.00    David  2023-04-20    9999999.00         HR

In [10]:
# check data types again to see if they are correct

employees.dtypes

User_ID         float64
Name             object
HireDate         object
Compensation    float64
Dept             object
dtype: object

In [11]:
# change data type of EmployeeID to string

employees['User_ID'] = employees['User_ID'].astype(str)

In [12]:
# check the data type again to confirm the change

employees.dtypes

User_ID          object
Name             object
HireDate         object
Compensation    float64
Dept             object
dtype: object

In [13]:
# check the dtypes again to confirm the change

employees.dtypes

User_ID          object
Name             object
HireDate         object
Compensation    float64
Dept             object
dtype: object

In [14]:
# check the stats

employees.describe()

       Compensation
count         88.00
mean      415056.78
std      1811039.09
min        60000.00
25%        70000.00
50%        75000.00
75%        85000.00
max      9999999.00

In [15]:
# testing to_numeric() function to convert Compensation to numeric

employees['Compensation'] = pd.to_numeric(employees['Compensation'], errors='coerce')

In [16]:
# view data types again to confirm the change
employees.dtypes

User_ID          object
Name             object
HireDate         object
Compensation    float64
Dept             object
dtype: object

In [17]:
employees.describe()

       Compensation
count         88.00
mean      415056.78
std      1811039.09
min        60000.00
25%        70000.00
50%        75000.00
75%        85000.00
max      9999999.00

In [18]:
# convert blanks to null/na values
employees.replace('', pd.NA, inplace=True)

In [19]:
# count nulls

employees.isnull().sum()

User_ID          0
Name             0
HireDate         0
Compensation    17
Dept             0
dtype: int64

In [20]:
# view nulls in user id column

employees[employees['User_ID'].isnull()]

Empty DataFrame
Columns: [User_ID, Name, HireDate, Compensation, Dept]
Index: []

In [21]:
# employee with null user id has all other data so we keep the row and try to find the user ID from stakeholders.

In [22]:
# view nulls in Compensation column

employees[employees['Compensation'].isnull()]

    User_ID     Name    HireDate  Compensation       Dept
2     103.0  Charlie  2023-03-15           NaN  Marketing
10    110.0     Judy  2023-10-10           NaN  Marketing
17    117.0    Peggy  2024-03-15           NaN         IT
22    122.0   Ursula  2024-06-01           NaN      Sales
30    130.0  Charlie  2023-03-15           NaN  Marketing
37    137.0     Judy  2023-10-10           NaN  Marketing
43    143.0    Peggy  2024-03-15           NaN         IT
48    148.0   Ursula  2024-06-01           NaN      Sales
57    157.0   Casper  2023-03-15           NaN  Marketing
64    164.0     Jake  2023-10-10           NaN  Marketing
70    170.0   Parker  2024-03-15           NaN         IT
75    175.0     Vera  2024-06-01           NaN      Sales
83    183.0     Dana  2023-03-15           NaN  Marketing
90    190.0     Karl  2023-10-10           NaN  Marketing
96    196.0     Reed  2024-03-15           NaN         IT
103   110.0     Judy  2023-10-10           NaN  Marketing
104   117.0    Peggy  2024-03-15           NaN         IT

In [23]:
# critical compensation data is missing so delete the row (if the compensation data cannot be found from stakeholders). delete the entire row for now.

employees.dropna(subset=['Compensation'], inplace=True)

In [24]:
#  Recheck nulls in Compensation column to confirm the change

employees[employees['Compensation'].isnull()]

Empty DataFrame
Columns: [User_ID, Name, HireDate, Compensation, Dept]
Index: []

In [25]:
# test for duplicate rows   

employees[employees.duplicated(keep=False)]

    User_ID   Name    HireDate  Compensation Dept
0     101.0  Alice  2023-01-01      75000.00   IT
3     101.0  Alice  2023-01-01      75000.00   IT
4     104.0  David  2023-04-20    9999999.00   HR
14    104.0  David  2023-04-20    9999999.00   HR
54    101.0  Alice  2023-01-01      75000.00   IT
101   101.0  Alice  2023-01-01      75000.00   IT
102   104.0  David  2023-04-20    9999999.00   HR

In [26]:
# drop duplicate rows if any

employees.drop_duplicates(inplace=True)

In [27]:
# confirm that duplicates were dropped 

employees[employees.duplicated(keep=False)]

Empty DataFrame
Columns: [User_ID, Name, HireDate, Compensation, Dept]
Index: []